version: "2"

linters:
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # Allow usage of deprecated resource.Create/Read/Update/Delete methods
    # These are still valid and working, just have newer Context alternatives
    - "SA1019: resource.Create is deprecated"
    - "SA1019: resource.Read is deprecated" 
    - "SA1019: resource.Update is deprecated"
    - "SA1019: resource.Delete is deprecated"

run:
  timeout: 5m
  skip-dirs:
    - third_party
    - builtin
    - examples