version: "2"

linters:
  enable:
    - copyloopvar
    - durationcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - unconvert
    - unparam
    - unused
  disable:
    - errcheck     # Too many false positives with defer resp.Body.Close()
    - staticcheck  # SA1019 warnings for deprecated resource methods that are still valid to check

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m